CREATE TABLE UnitedStates (
     Name varchar(30) NOT NULL PRIMARY KEY
    ,Abbreviation char(2) NOT NULL
    ,Type varchar(21) NOT NULL
  )
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Alabama', 'AL', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Alaska', 'AK', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Arizona', 'AZ', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Arkansas', 'AR', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('California', 'CA', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Colorado', 'CO', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Connecticut', 'CT', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Delaware', 'DE', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Florida', 'FL', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Georgia', 'GA', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Hawaii', 'HI', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Idaho', 'ID', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Illinois', 'IL', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Indiana', 'IN', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Iowa', 'IA', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Kansas', 'KS', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Kentucky', 'KY', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Louisiana', 'LA', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Maine', 'ME', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Maryland', 'MD', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Massachusetts', 'MA', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Michigan', 'MI', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Minnesota', 'MN', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Mississippi', 'MS', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Missouri', 'MO', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Montana', 'MT', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Nebraska', 'NE', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Nevada', 'NV', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('New Hampshire', 'NH', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('New Jersey', 'NJ', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('New Mexico', 'NM', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('New York', 'NY', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('North Carolina', 'NC', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('North Dakota', 'ND', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Ohio', 'OH', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Oklahoma', 'OK', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Oregon', 'OR', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Pennsylvania', 'PA', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Rhode Island', 'RI', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('South Carolina', 'SC', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('South Dakota', 'SD', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Tennessee', 'TN', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Texas', 'TX', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Utah', 'UT', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Vermont', 'VT', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Virginia', 'VA', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Washington', 'WA', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('West Virginia', 'WV', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Wisconsin', 'WI', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Wyoming', 'WY', 'State')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('District of Columbia', 'DC', 'FederalDistrict')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('American Samoa', 'AS', 'InsularArea')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Guam', 'GU', 'InsularArea')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Northern Mariana Islands', 'MP', 'InsularArea')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Puerto Rico', 'PR', 'InsularArea')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Virgin Islands', 'VI', 'InsularArea')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Federated States of Micronesia', 'FM', 'FreelyAssociatedState')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Marshall Islands', 'MH', 'FreelyAssociatedState')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Palau', 'PW', 'FreelyAssociatedState')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Armed Forces Africa', 'AE', 'Military')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Armed Forces Americas', 'AA', 'Military')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Armed Forces Canada', 'AE', 'Military')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Armed Forces Europe', 'AE', 'Military')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Armed Forces Middle East', 'AE', 'Military')
INSERT INTO UnitedStates (Name, Abbreviation, Type) VALUES ('Armed Forces Pacific', 'AP', 'Military')
